Repository RicoSuter/NSwag, pull requests merged in 2019-04, with the labels that each got.

#1973 Operation generation mode from first tag and path segments
  src/NSwag.CodeGeneration/OperationNameGenerators/MultipleClientsFromFirstTagAndPathSegmentsOperationNameGenerator.cs
  src/NSwag.Commands/Commands/CodeGeneration/OperationGenerationMode.cs
  src/NSwag.Commands/OperationGenerationModeConverter.cs
  src/NSwag.SwaggerGeneration.WebApi.Tests/NSwag.SwaggerGeneration.WebApi.Tests.csproj
  src/NSwag.SwaggerGeneration.WebApi.Tests/OperationNameGenerator/MultipleClientsFromFirstTagAndPathSegmentsOperationNameGeneratorTests.cs
Labels: state: ready

#1942 Support to ASP.Net Core ActionResult Type on controller generator
  src/NSwag.CodeGeneration.CSharp.Tests/ControllerGenerationFormatTests.cs
  src/NSwag.CodeGeneration.CSharp/Models/CSharpControllerOperationModel.cs
  src/NSwag.CodeGeneration.CSharp/Models/CSharpOperationModel.cs
  src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpControllerGenerator.cs
  src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpControllerGeneratorSettings.cs
  src/NSwag.Commands/Commands/CodeGeneration/SwaggerToCSharpControllerCommand.cs
  src/NSwagStudio/Views/CodeGenerators/SwaggerToCSharpControllerGeneratorView.xaml
Labels: state: ready

#2067 Fix overwriting global consumes and produces sections
  src/NSwag.SwaggerGeneration.AspNetCore.Tests.Web/Controllers/Requests/ConsumesController.cs
  src/NSwag.SwaggerGeneration.AspNetCore.Tests.Web/Controllers/Requests/MultipartConsumesController.cs
  src/NSwag.SwaggerGeneration.AspNetCore.Tests.Web/Controllers/Responses/JsonProducesController.cs
  src/NSwag.SwaggerGeneration.AspNetCore.Tests.Web/Controllers/Responses/TextProducesController.cs
  src/NSwag.SwaggerGeneration.AspNetCore.Tests/Requests/ConsumesTests.cs
  src/NSwag.SwaggerGeneration.AspNetCore.Tests/Responses/ProducesTests.cs
  src/NSwag.SwaggerGeneration.AspNetCore.Tests/Responses/ResponseAttributesTests.cs
  src/NSwag.SwaggerGeneration.AspNetCore/AspNetCoreToSwaggerGenerator.cs
Labels: state: ready

#2066 Use controller name from ApiExplorer instead of custom logic for AspNetCoreToSwaggerGenerator
  src/NSwag.SwaggerGeneration.AspNetCore/AspNetCoreToSwaggerGeneratorSettings.cs
  src/NSwag.SwaggerGeneration.AspNetCore/Processors/AspNetCoreOperationTagsProcessor.cs
  src/NSwag.SwaggerGeneration/Processors/Collections/OperationProcessorCollection.cs
  src/NSwag.SwaggerGeneration/Processors/OperationTagsProcessor.cs
Labels: state: await-changes

#2104 Improve IsXmlBodyParameter, IsBinaryBodyParameter and SwaggerRespons.IsBinary()
  src/NSwag.Core.Tests/SwaggerResponseTests.cs
  src/NSwag.Core/SwaggerParameter.cs
  src/NSwag.Core/SwaggerResponse.cs
Labels: state: ready

#2096 Update to latest ASP.NET Core versions (CLI)
  src/NSwag.Commands/NSwag.Commands.csproj
  src/NSwag.Console.x86/NSwag.Console.x86.csproj
  src/NSwag.Console/NSwag.Console.csproj
Labels: state: ready

#2105 Improve swagger middlewares for extensibility
  src/NSwag.AspNet.Owin/Middlewares/SwaggerDocumentMiddleware.cs
  src/NSwag.AspNetCore/Middlewares/SwaggerDocumentMiddleware.cs
Labels: state: ready

#1965 #1955 C# Web API Controller : Generator does not handle "required" fi…
  src/NSwag.CodeGeneration.CSharp.Tests/ControllerGenerationFormatTests.cs
  src/NSwag.CodeGeneration.CSharp.Tests/UseCancellationTokenTests.cs
  src/NSwag.CodeGeneration.CSharp/Models/CSharpControllerTemplateModel.cs
  src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpControllerGeneratorSettings.cs
  src/NSwag.CodeGeneration.CSharp/Templates/Controller.liquid
Labels: state: await-changes, state: await-response

#2130 Feature/adds ability to host on different urls
  src/NSwag.AspNetCore/Extensions/NSwagApplicationBuilderExtensions.cs
  src/NSwag.AspNetCore/Middlewares/SwaggerDocumentMiddleware.cs
  src/NSwag.AspNetCore/SwaggerDocumentMiddlewareSettings.cs
  src/NSwag.Sample.NETCore22/Startup.cs
Labels: state: ready
