Repository RicoSuter/NSwag, pull requests merged in 2020-05, with the labels that each got.

#2821 Fixes #2820
  src/NSwag.Core.Yaml.Tests/YamlDocumentTests.cs
  src/NSwag.Core/OpenApiPathItem.cs
Labels: state: await-changes

#2819 Support query params expansion when explode is true and style is form
  src/NSwag.CodeGeneration.CSharp.Tests/QueryParameterTests.cs
  src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.QueryParameter.liquid
  src/NSwag.CodeGeneration/Models/ParameterModelBase.cs
Labels: state: await-response

#2655 Read some System.Text.Json options
  src/NSwag.AspNet.Owin/NSwag.AspNet.Owin.csproj
  src/NSwag.AspNet.WebApi/NSwag.AspNet.WebApi.csproj
  src/NSwag.AssemblyLoader/NSwag.AssemblyLoader.csproj
  src/NSwag.CodeGeneration.CSharp/NSwag.CodeGeneration.CSharp.csproj
  src/NSwag.CodeGeneration.TypeScript/NSwag.CodeGeneration.TypeScript.csproj
  src/NSwag.CodeGeneration/NSwag.CodeGeneration.csproj
  src/NSwag.Commands/Commands/Generation/OpenApiGeneratorCommandBase.cs
  src/NSwag.Commands/NSwag.Commands.csproj
  src/NSwag.Core.Yaml/NSwag.Core.Yaml.csproj
  src/NSwag.Core/NSwag.Core.csproj
  src/NSwag.Demo.Web/NSwag.Demo.Web.csproj
  src/NSwag.Demo.Web/packages.config
  src/NSwag.Generation.AspNetCore/AspNetCoreOpenApiDocumentGenerator.cs
  src/NSwag.Generation.AspNetCore/NSwag.Generation.AspNetCore.csproj
  src/NSwag.Generation.AspNetCore3.Tests/NSwag.Generation.AspNetCore3.Tests.csproj
  src/NSwag.Generation.AspNetCore3.Tests/SystemTextJsonTests.cs
  src/NSwag.Generation.WebApi.Tests/NSwag.Generation.WebApi.Tests.csproj
  src/NSwag.Generation.WebApi.Tests/packages.config
  src/NSwag.Generation.WebApi/NSwag.Generation.WebApi.csproj
  src/NSwag.Generation/NSwag.Generation.csproj
  src/NSwag.Integration.WebAPI/NSwag.Integration.WebAPI.csproj
  src/NSwag.Integration.WebAPI/packages.config
  src/NSwag.Min.sln
  src/NSwag.Sample.NetGlobalAsax/NSwag.Sample.NetGlobalAsax.csproj
  src/NSwag.Sample.NetGlobalAsax/packages.config
  src/NSwag.sln
  src/NSwagStudio/NSwagStudio.csproj
  src/NSwagStudio/packages.config
Labels: state: ready
